### ISSUE TITLE
[BUG] IceandFire myrmex spartan weapons do not correctly apply the damage bonus.

### ISSUE THREAD

**Issue by elephantae** [CheezedFish/SpartanCompatibility#12]
Description
All of the weapons made of both types of myrmex chitin from the spartanfire mod(ex: desert myrmex longsword, jungle myrmex throwing knife) deal an incorrect amount of damage on hit/throw. The damage bonus upon hitting non-arthropod mobs is supposed to be 4, and this can be confirmed by hitting anything with a myrmex weapon that does less than 4 base damage or by looking at the description for the myrmex sword. Thus, i would expect 4 to be added to my damage when hitting a non-arthropod mob, however this does not happen as it seems to take the higher of the 2 numbers 4 and the base damage rather than adding them.

To Reproduce
Steps to reproduce the behavior:Take any myrmex weapon from the spartanfire mod and test damage compared to a myrmex sword on an arthropod and a non arthropod. Also test dagger and throwables and observe them deal 4 damage.

Expected behavior
The damage bonus is expected to be added to the weapon damage rather than be a minimum.

Screenshots

![image](https://user-images.githubusercontent.com/36980723/79599771-50b0a580-80a3-11ea-95cc-76b83db2f7ec.png)
![image](https://user-images.githubusercontent.com/36980723/79599788-573f1d00-80a3-11ea-9b7f-61abb27958d6.png)
![image](https://user-images.githubusercontent.com/36980723/79599811-5dcd9480-80a3-11ea-8d2a-10704b3ba5f0.png)
![image](https://user-images.githubusercontent.com/36980723/79599821-61f9b200-80a3-11ea-8f99-74bfd362b017.png)
![image](https://user-images.githubusercontent.com/36980723/79599830-6625cf80-80a3-11ea-9f2d-80b5e201dc6c.png)
![image](https://user-images.githubusercontent.com/36980723/79599835-6a51ed00-80a3-11ea-8903-c1bfd7b08d71.png)

Testing was done in the modpack Rebirth of the Night

**Comment by CheezedFish** [comment]
Ah, there seems to be a misunderstanding here. Spartan Compat doesn't add in support for Ice and Fire materials, that would actually be handled by Spartan and Fire, another Spartan Weaponry addon. The mod id for the weapon you showed is "spartanfire" not "spartancompat". I would definitely encourage you to forward this issue to their repository however. You can report it [here](https://github.com/ChaosBuffalo/SpartanFire/issues).

**Comment by elephantae** [comment]
thank you, i'm sorry for the misunderstanding. I have made an issue on the spartanfire github and adopted a custom hotfix for the time being.
