### ISSUE TITLE
Check aether compat, for a new update has come to aether that broke a few addons

### ISSUE THREAD

**Issue by Sunconure11** [CheezedFish/SpartanCompatibility#18]
@CheezedFish 

Recent aether update broke several addons. I would advise you check your mod, to make sure it's still compatible.

**Comment by JOqupa** [comment]
I was going to write that. It crush for me.

**Comment by CheezedFish** [comment]
Version 1.2.3 has been uploaded to curseforge that fixes this compatibility. Just waiting on the approval process.
