### ISSUE TITLE
Crash caused by Spartan Compatibility

### ISSUE THREAD

**Issue by maxim0p** [CheezedFish/SpartanCompatibility#3]
Log:
https://paste.dimdev.org/uvopixihax.mccrash

It crashes after I kill any mob, uninstalling spartan compatibility gets rid of the problem, so somewhere there is causing the error.

`    at com.cheezedfish.spartancompat.event.SpartanCompatibilityEventHandler.onEntityDropLoot(SpartanCompatibilityEventHandler.java:33)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1734_SpartanCompatibilityEventHandler_onEntityDropLoot_LivingDropsEvent.invoke(.dynamic))`

**Comment by CheezedFish** [comment]
Resolved in version 1.1.1.
