### ISSUE TITLE
Crash Loading with Better With Mods [SC 1.2.0]

### ISSUE THREAD

**Issue by ObliviousSpartan** [CheezedFish/SpartanCompatibility#6]
Hi, I'm the mod author of Spartan Weaponry. I decided to try out your mod when someone told me about it.

I found that when loading this mod with Better With Mods, it causes a crash due to one of the recipes not being correctly set.
Crash report here: [crash-2020-02-04_14.46.23-client.txt](https://github.com/CheezedFish/SpartanCompatibility/files/4151059/crash-2020-02-04_14.46.23-client.txt)

I checked your source code here: https://github.com/CheezedFish/SpartanCompatibility/blob/master/src/main/java/com/cheezedfish/spartancompat/init/ItemRegistrySC.java
Inthe method "registerLongbowRecipeBWM()" (line 471), it seems like that you've used the "W" key in your anvil recipe without properly defining it.

Thanks for making this mod too. It looks awesome!

**Comment by CheezedFish** [comment]
Noted and patched for v1.2.1. Thank you!

**Comment by ObliviousSpartan** [comment]
Wow that was really fast. Thanks again.
