### ISSUE TITLE
Uncraftable Aether Weapons due to a recipe error for Skyroot Handles/Poles [SC 1.2.0]

### ISSUE THREAD

**Issue by ObliviousSpartan** [CheezedFish/SpartanCompatibility#7]
Hi again,
When I was testing the mod without BWM due to the crash (issue #6), I also noticed that there is an error with Skyroot Handles/Poles not being craftable. 
I took a deeper look into it and noticed that the recipe does exist, but it results in the standard Spartan Weaponry Handles and Poles being crafted instead of the Skyroot ones that you have made.
Unfortunately, it also means that any Aether Weapon from your mod is uncraftable in the meantime in Survival mode.
Thanks again.

**Comment by CheezedFish** [comment]
Yikes, I really gotta be more careful when setting these recipes up. That's what I get for doing them at 1 AM I guess. Nevertheless, fixed in f09a31a. Thanks for letting me know about these, gotta up my playtesting game.
